### ISSUE TITLE
YAML import not working?

### ISSUE THREAD

**Issue by stijnb1234** [ever-co/ever-traduora#377]
**Describe the bug**
I'm trying to import a yaml file, but I get: "Error, resource not found"

**To Reproduce**
1. Create a new project
2. Go to Import and upload a YAML file.
3. Select a language and choose Import
4. See the error

**Expected behavior**
It should just import

**Screenshots**
![image](https://user-images.githubusercontent.com/27051051/226177248-4fc44fb0-117f-4286-b9e8-7b7fa5fae54a.png)

** Environment (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows
 - Browser: Brave (tried Firefox too)
 - Version: `latest`

**Additional context**
My docker-compose.yaml file (created in Portainer):
```
version: '3.7'

services:
  traduora:
    image: everco/ever-traduora:latest
    container_name: traduora
    build:
      context: .
      dockerfile: Dockerfile
      args:
          NODE_ENV: ${NODE_ENV:-development}
    environment:
      TR_DB_TYPE: mysql
      TR_DB_USER: tr
      TR_DB_PASSWORD: removed_for_privacy
      TR_DB_DATABASE: tr_dev
      TR_DB_HOST: mysqldb
      TR_DB_PORT: 3306
      NODE_ENV: ${NODE_ENV:-development}    
    entrypoint: './docker-entrypoint.compose.sh'
    restart: on-failure
    depends_on:
      - mysqldb
    links:
      - mysqldb:${TR_DB_HOST:-mysqldb}      
    networks:
      - overlay

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: tr_dev
      MYSQL_USER: tr
      MYSQL_PASSWORD: removed_for_privacy
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    networks:
      - overlay

networks:
  overlay:
      driver: bridge
```
